/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package unittest;

import model.Category;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import static org.junit.Assert.*;

public class AppTest {
    private EntityManager em;

    @Before
    public void init() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("dbDS");
        em = emf.createEntityManager();
    }

    @After
    public void close() {
        em.getEntityManagerFactory().close();
        em.close();
    }

    //    @Test public void shouldStartHibernate() {
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("dbDS");
//        EntityManager entityManager = emf.createEntityManager();
//    }
    @Test
    public void shouldPersistCategory() {
        Category cat = new Category();
        cat.setTitle("new Category");
        em.persist(cat);
    }

}


